// ============================================================
// FitZone Mock Data — realistic Indian fitness industry data
// ============================================================

// ---- Images (real Unsplash photo IDs) ----
const IMG = {
  gyms: [
    "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1570829460005-c840387bb1ca?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1637666062717-1c6bcfa4a4df?w=800&h=500&fit=crop",
  ],
  trainers: [
    "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
  ],
  food: [
    "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=300&fit=crop",
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop",
    "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=300&h=300&fit=crop",
    "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=300&h=300&fit=crop",
    "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=300&h=300&fit=crop",
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300&h=300&fit=crop",
  ],
  yoga: [
    "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=500&fit=crop",
    "https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&h=500&fit=crop",
  ],
};

// ---- Gyms ----
export const gyms = [
  {
    id: "gym-1",
    name: "Iron Paradise Fitness",
    tagline: "Where Champions Are Forged",
    address: "42, 3rd Cross, Koramangala 5th Block, Bangalore - 560095",
    phone: "+91 98456 12340",
    email: "info@ironparadise.fit",
    rating: 4.7,
    reviewCount: 342,
    distance: 1.2,
    priceRange: { min: 2000, max: 8000 },
    image: IMG.gyms[0],
    gallery: [IMG.gyms[0], IMG.gyms[1], IMG.gyms[2]],
    amenities: ["AC", "Parking", "Steam Room", "Sauna", "Locker", "Wifi", "Changing Room", "Shower"],
    classTypes: ["Yoga", "HIIT", "CrossFit", "Zumba", "Pilates", "Boxing"],
    operatingHours: { open: "5:00 AM", close: "11:00 PM" },
    isOpen: true,
    isPremium: true,
    memberCount: 850,
    trainersCount: 12,
    established: 2018,
    branches: ["Koramangala", "Indiranagar", "HSR Layout"],
  },
  {
    id: "gym-2",
    name: "Zen Yoga Studio",
    tagline: "Find Your Inner Balance",
    address: "15, 1st Main, Indiranagar, Bangalore - 560038",
    phone: "+91 98765 00123",
    email: "hello@zenyoga.in",
    rating: 4.9,
    reviewCount: 218,
    distance: 2.4,
    priceRange: { min: 1500, max: 4000 },
    image: IMG.yoga[0],
    gallery: [IMG.yoga[0], IMG.yoga[1], IMG.yoga[2]],
    amenities: ["AC", "Changing Room", "Shower", "Meditation Room", "Herbal Tea Corner"],
    classTypes: ["Hatha Yoga", "Vinyasa", "Ashtanga", "Meditation", "Pilates", "Pranayama"],
    operatingHours: { open: "5:30 AM", close: "9:00 PM" },
    isOpen: true,
    isPremium: false,
    memberCount: 340,
    trainersCount: 6,
    established: 2020,
    branches: ["Indiranagar"],
  },
  {
    id: "gym-3",
    name: "CrossFit Bangalore",
    tagline: "Forging Elite Fitness",
    address: "78, Outer Ring Road, Marathahalli, Bangalore - 560037",
    phone: "+91 88765 43210",
    email: "coach@crossfitblr.com",
    rating: 4.6,
    reviewCount: 189,
    distance: 5.1,
    priceRange: { min: 3500, max: 7000 },
    image: IMG.gyms[3],
    gallery: [IMG.gyms[3], IMG.gyms[4], IMG.gyms[5]],
    amenities: ["Parking", "Shower", "Changing Room", "CrossFit Rig", "Outdoor Area"],
    classTypes: ["CrossFit", "Olympic Lifting", "HIIT", "Functional Training", "Boot Camp"],
    operatingHours: { open: "5:00 AM", close: "10:00 PM" },
    isOpen: true,
    isPremium: true,
    memberCount: 280,
    trainersCount: 8,
    established: 2019,
    branches: ["Marathahalli", "Whitefield"],
  },
  {
    id: "gym-4",
    name: "FitBudget Gym",
    tagline: "Premium Fitness, Affordable Price",
    address: "23, 4th Cross, BTM Layout 2nd Stage, Bangalore - 560076",
    phone: "+91 77654 32100",
    email: "join@fitbudget.in",
    rating: 4.2,
    reviewCount: 567,
    distance: 3.3,
    priceRange: { min: 800, max: 2500 },
    image: IMG.gyms[6],
    gallery: [IMG.gyms[6], IMG.gyms[7], IMG.gyms[0]],
    amenities: ["AC", "Locker", "Changing Room"],
    classTypes: ["Zumba", "Yoga", "General Fitness"],
    operatingHours: { open: "5:00 AM", close: "11:00 PM" },
    isOpen: true,
    isPremium: false,
    memberCount: 1200,
    trainersCount: 5,
    established: 2021,
    branches: ["BTM Layout"],
  },
  {
    id: "gym-5",
    name: "She Fitness",
    tagline: "Empowering Women Through Fitness",
    address: "56, 12th Main, Jayanagar 4th Block, Bangalore - 560041",
    phone: "+91 96543 21009",
    email: "hello@shefitness.in",
    rating: 4.8,
    reviewCount: 156,
    distance: 4.0,
    priceRange: { min: 2000, max: 6000 },
    image: IMG.gyms[4],
    gallery: [IMG.gyms[4], IMG.yoga[1], IMG.yoga[2]],
    amenities: ["AC", "Parking", "Steam Room", "Locker", "Wifi", "Childcare Area", "Women-Only"],
    classTypes: ["Yoga", "Zumba", "Pilates", "Dance Fitness", "HIIT", "Kickboxing"],
    operatingHours: { open: "6:00 AM", close: "9:00 PM" },
    isOpen: false,
    isPremium: true,
    memberCount: 420,
    trainersCount: 8,
    established: 2019,
    branches: ["Jayanagar", "JP Nagar"],
  },
  {
    id: "gym-6",
    name: "Titan Strength Hub",
    tagline: "Lift Heavy, Live Strong",
    address: "99, 5th Cross, Whitefield Main Road, Bangalore - 560066",
    phone: "+91 99876 54320",
    email: "info@titanstrength.in",
    rating: 4.5,
    reviewCount: 298,
    distance: 7.8,
    priceRange: { min: 2500, max: 10000 },
    image: IMG.gyms[5],
    gallery: [IMG.gyms[5], IMG.gyms[7], IMG.gyms[2]],
    amenities: ["AC", "Parking", "Steam Room", "Sauna", "Locker", "Wifi", "Supplement Bar", "Boxing Ring"],
    classTypes: ["Powerlifting", "Bodybuilding", "Boxing", "MMA", "HIIT", "Functional Training"],
    operatingHours: { open: "4:30 AM", close: "11:30 PM" },
    isOpen: true,
    isPremium: true,
    memberCount: 650,
    trainersCount: 14,
    established: 2017,
    branches: ["Whitefield", "Electronic City", "Sarjapur Road"],
  },
];

// ---- Trainers ----
export const trainers = [
  {
    id: "trainer-1",
    name: "Coach Arjun Mehta",
    avatar: IMG.trainers[0],
    specializations: ["Weight Loss", "Functional Training", "HIIT"],
    certifications: ["ACE Certified", "NASM-CPT", "First Aid"],
    experience: 5,
    rating: 4.8,
    reviewCount: 124,
    pricePerSession: 1200,
    bio: "Specializing in body transformations with a focus on sustainable habits. Helped 200+ clients achieve their fitness goals through structured programming and accountability coaching.",
    clients: 18,
    sessionsCompleted: 2340,
    availability: "Mon-Sat, 6 AM - 2 PM",
    gym: "Iron Paradise Fitness",
    gymId: "gym-1",
    isVerified: true,
    languages: ["English", "Hindi", "Kannada"],
  },
  {
    id: "trainer-2",
    name: "Priya Nair",
    avatar: IMG.trainers[3],
    specializations: ["Yoga", "Flexibility", "Meditation", "Prenatal Fitness"],
    certifications: ["RYT-500", "Prenatal Yoga Certified"],
    experience: 8,
    rating: 4.9,
    reviewCount: 198,
    pricePerSession: 1500,
    bio: "A passionate yoga instructor with 8 years of experience. My classes blend traditional Ashtanga with modern flow techniques to create a holistic mind-body experience.",
    clients: 25,
    sessionsCompleted: 4120,
    availability: "Mon-Sun, 5:30 AM - 12 PM",
    gym: "Zen Yoga Studio",
    gymId: "gym-2",
    isVerified: true,
    languages: ["English", "Malayalam", "Hindi"],
  },
  {
    id: "trainer-3",
    name: "Vikram Singh",
    avatar: IMG.trainers[1],
    specializations: ["Powerlifting", "Bodybuilding", "Strength Training"],
    certifications: ["ISSA Certified", "Precision Nutrition L1"],
    experience: 10,
    rating: 4.7,
    reviewCount: 87,
    pricePerSession: 2000,
    bio: "Former state-level powerlifter turned coach. I train athletes and serious lifters who want to push their limits safely. Competition prep is my specialty.",
    clients: 12,
    sessionsCompleted: 3800,
    availability: "Mon-Sat, 7 AM - 6 PM",
    gym: "Titan Strength Hub",
    gymId: "gym-6",
    isVerified: true,
    languages: ["English", "Hindi", "Punjabi"],
  },
  {
    id: "trainer-4",
    name: "Sneha Reddy",
    avatar: IMG.trainers[5],
    specializations: ["Zumba", "Dance Fitness", "Weight Loss", "HIIT"],
    certifications: ["Zumba Licensed Instructor", "ACE Group Fitness"],
    experience: 4,
    rating: 4.6,
    reviewCount: 156,
    pricePerSession: 800,
    bio: "Bringing energy and fun to every session! My dance-based fitness classes help you burn 500-800 calories while having the time of your life.",
    clients: 30,
    sessionsCompleted: 1560,
    availability: "Mon-Fri, 4 PM - 9 PM",
    gym: "She Fitness",
    gymId: "gym-5",
    isVerified: true,
    languages: ["English", "Telugu", "Hindi"],
  },
  {
    id: "trainer-5",
    name: "Aditya Kapoor",
    avatar: IMG.trainers[4],
    specializations: ["CrossFit", "Olympic Lifting", "Endurance"],
    certifications: ["CrossFit L2 Trainer", "USAW Sports Performance"],
    experience: 6,
    rating: 4.8,
    reviewCount: 92,
    pricePerSession: 1800,
    bio: "CrossFit Games competitor and Level 2 trainer. I build resilient athletes through varied functional movements performed at high intensity.",
    clients: 15,
    sessionsCompleted: 2890,
    availability: "Mon-Sat, 5 AM - 1 PM",
    gym: "CrossFit Bangalore",
    gymId: "gym-3",
    isVerified: true,
    languages: ["English", "Hindi"],
  },
  {
    id: "trainer-6",
    name: "Deepa Joshi",
    avatar: IMG.trainers[6],
    specializations: ["Pilates", "Rehabilitation", "Posture Correction"],
    certifications: ["STOTT Pilates Certified", "Physiotherapy Diploma"],
    experience: 7,
    rating: 4.9,
    reviewCount: 67,
    pricePerSession: 1600,
    bio: "With a background in physiotherapy, I specialize in corrective exercise and injury prevention. My Pilates sessions are designed to strengthen, align, and heal.",
    clients: 14,
    sessionsCompleted: 2100,
    availability: "Tue-Sat, 8 AM - 5 PM",
    gym: "Iron Paradise Fitness",
    gymId: "gym-1",
    isVerified: true,
    languages: ["English", "Hindi", "Marathi"],
  },
  {
    id: "trainer-7",
    name: "Ravi Kumar",
    avatar: IMG.trainers[2],
    specializations: ["Boxing", "MMA", "Self Defense"],
    certifications: ["Boxing Coach Level 3", "Krav Maga Instructor"],
    experience: 9,
    rating: 4.5,
    reviewCount: 73,
    pricePerSession: 1400,
    bio: "Former amateur boxer with a passion for combat sports. I train everyone from beginners learning self-defense to competitive fighters preparing for bouts.",
    clients: 20,
    sessionsCompleted: 3200,
    availability: "Mon-Sat, 3 PM - 10 PM",
    gym: "Titan Strength Hub",
    gymId: "gym-6",
    isVerified: true,
    languages: ["English", "Hindi", "Tamil"],
  },
  {
    id: "trainer-8",
    name: "Ananya Sharma",
    avatar: IMG.trainers[7],
    specializations: ["Weight Loss", "Nutrition Coaching", "General Fitness"],
    certifications: ["NASM-CPT", "Precision Nutrition L2", "Pre/Post Natal"],
    experience: 3,
    rating: 4.4,
    reviewCount: 45,
    pricePerSession: 900,
    bio: "I believe fitness should be accessible and enjoyable for everyone. My approach combines smart training with practical nutrition advice tailored for Indian diets.",
    clients: 22,
    sessionsCompleted: 980,
    availability: "Mon-Fri, 6 AM - 3 PM",
    gym: "FitBudget Gym",
    gymId: "gym-4",
    isVerified: true,
    languages: ["English", "Hindi"],
  },
];

// ---- Classes ----
export const classes = [
  { id: "class-1", name: "Morning Flow Yoga", type: "Yoga", trainer: "Priya Nair", trainerId: "trainer-2", gym: "Zen Yoga Studio", gymId: "gym-2", day: "Mon, Wed, Fri", time: "6:00 AM", duration: 60, capacity: 20, booked: 18, image: IMG.yoga[0], difficulty: "All Levels", room: "Studio A" },
  { id: "class-2", name: "HIIT Burn", type: "HIIT", trainer: "Coach Arjun Mehta", trainerId: "trainer-1", gym: "Iron Paradise Fitness", gymId: "gym-1", day: "Mon, Tue, Thu", time: "7:00 AM", duration: 45, capacity: 25, booked: 25, image: IMG.gyms[1], difficulty: "Intermediate", room: "Main Floor" },
  { id: "class-3", name: "CrossFit WOD", type: "CrossFit", trainer: "Aditya Kapoor", trainerId: "trainer-5", gym: "CrossFit Bangalore", gymId: "gym-3", day: "Mon-Sat", time: "6:00 AM", duration: 60, capacity: 15, booked: 12, image: IMG.gyms[3], difficulty: "Advanced", room: "CrossFit Box" },
  { id: "class-4", name: "Zumba Dance Party", type: "Zumba", trainer: "Sneha Reddy", trainerId: "trainer-4", gym: "She Fitness", gymId: "gym-5", day: "Tue, Thu, Sat", time: "5:00 PM", duration: 50, capacity: 30, booked: 28, image: IMG.gyms[4], difficulty: "Beginner", room: "Dance Studio" },
  { id: "class-5", name: "Power Pilates", type: "Pilates", trainer: "Deepa Joshi", trainerId: "trainer-6", gym: "Iron Paradise Fitness", gymId: "gym-1", day: "Tue, Thu", time: "8:00 AM", duration: 55, capacity: 15, booked: 10, image: IMG.yoga[2], difficulty: "Intermediate", room: "Studio B" },
  { id: "class-6", name: "Boxing Fundamentals", type: "Boxing", trainer: "Ravi Kumar", trainerId: "trainer-7", gym: "Titan Strength Hub", gymId: "gym-6", day: "Mon, Wed, Fri", time: "6:00 PM", duration: 60, capacity: 12, booked: 9, image: IMG.gyms[5], difficulty: "Beginner", room: "Boxing Ring" },
  { id: "class-7", name: "Ashtanga Primary Series", type: "Yoga", trainer: "Priya Nair", trainerId: "trainer-2", gym: "Zen Yoga Studio", gymId: "gym-2", day: "Tue, Thu, Sat", time: "5:30 AM", duration: 90, capacity: 15, booked: 15, image: IMG.yoga[1], difficulty: "Advanced", room: "Studio A" },
  { id: "class-8", name: "Evening HIIT Circuit", type: "HIIT", trainer: "Ananya Sharma", trainerId: "trainer-8", gym: "FitBudget Gym", gymId: "gym-4", day: "Mon, Wed, Fri", time: "6:30 PM", duration: 40, capacity: 20, booked: 14, image: IMG.gyms[7], difficulty: "Beginner", room: "Group Area" },
  { id: "class-9", name: "Olympic Lifting Basics", type: "Olympic Lifting", trainer: "Aditya Kapoor", trainerId: "trainer-5", gym: "CrossFit Bangalore", gymId: "gym-3", day: "Wed, Sat", time: "8:00 AM", duration: 75, capacity: 10, booked: 7, image: IMG.gyms[3], difficulty: "Intermediate", room: "Lifting Platform" },
  { id: "class-10", name: "Meditation & Breathwork", type: "Meditation", trainer: "Priya Nair", trainerId: "trainer-2", gym: "Zen Yoga Studio", gymId: "gym-2", day: "Daily", time: "7:00 PM", duration: 30, capacity: 25, booked: 12, image: IMG.yoga[0], difficulty: "All Levels", room: "Meditation Room" },
  { id: "class-11", name: "Boot Camp", type: "Boot Camp", trainer: "Coach Arjun Mehta", trainerId: "trainer-1", gym: "Iron Paradise Fitness", gymId: "gym-1", day: "Sat", time: "7:00 AM", duration: 60, capacity: 30, booked: 22, image: IMG.gyms[2], difficulty: "All Levels", room: "Outdoor Area" },
  { id: "class-12", name: "Kickboxing Cardio", type: "Kickboxing", trainer: "Ravi Kumar", trainerId: "trainer-7", gym: "Titan Strength Hub", gymId: "gym-6", day: "Tue, Thu", time: "7:00 PM", duration: 50, capacity: 15, booked: 13, image: IMG.gyms[5], difficulty: "Intermediate", room: "Boxing Ring" },
  { id: "class-13", name: "Fat Burner Express", type: "HIIT", trainer: "Sneha Reddy", trainerId: "trainer-4", gym: "She Fitness", gymId: "gym-5", day: "Mon, Wed, Fri", time: "6:00 AM", duration: 30, capacity: 20, booked: 16, image: IMG.gyms[4], difficulty: "Beginner", room: "Main Floor" },
  { id: "class-14", name: "Posture Fix Pilates", type: "Pilates", trainer: "Deepa Joshi", trainerId: "trainer-6", gym: "Iron Paradise Fitness", gymId: "gym-1", day: "Sat", time: "10:00 AM", duration: 60, capacity: 12, booked: 8, image: IMG.yoga[2], difficulty: "All Levels", room: "Studio B" },
  { id: "class-15", name: "Strength Foundations", type: "Functional Training", trainer: "Vikram Singh", trainerId: "trainer-3", gym: "Titan Strength Hub", gymId: "gym-6", day: "Mon, Wed, Fri", time: "8:00 AM", duration: 60, capacity: 10, booked: 10, image: IMG.gyms[5], difficulty: "Beginner", room: "Strength Zone" },
];

// ---- Membership Plans ----
export const membershipPlans = [
  {
    id: "plan-basic",
    name: "Basic",
    price: 1999,
    duration: "month",
    color: "#6b7280",
    features: [
      { name: "Gym floor access", included: true },
      { name: "Group classes (4/month)", included: true },
      { name: "Personal training sessions", included: false },
      { name: "Shared locker", included: true },
      { name: "Steam / Sauna", included: false },
      { name: "Nutrition plan", included: false },
      { name: "AI workout plan", included: false },
      { name: "Guest passes", included: false },
      { name: "Multi-branch access", included: false },
      { name: "Body composition analysis", included: false },
    ],
    popular: false,
  },
  {
    id: "plan-pro",
    name: "Pro",
    price: 3999,
    duration: "month",
    color: "#6d28d9",
    features: [
      { name: "Gym floor access", included: true },
      { name: "Unlimited group classes", included: true },
      { name: "2 PT sessions/month", included: true },
      { name: "Dedicated locker", included: true },
      { name: "Steam / Sauna", included: true },
      { name: "Basic nutrition template", included: true },
      { name: "AI workout plan", included: true },
      { name: "1 guest pass/month", included: true },
      { name: "Home + 1 branch access", included: true },
      { name: "Quarterly body comp analysis", included: true },
    ],
    popular: true,
  },
  {
    id: "plan-elite",
    name: "Elite",
    price: 7999,
    duration: "month",
    color: "#f59e0b",
    features: [
      { name: "Gym floor access", included: true },
      { name: "Unlimited group classes", included: true },
      { name: "8 PT sessions/month", included: true },
      { name: "Premium dedicated locker", included: true },
      { name: "Steam / Sauna", included: true },
      { name: "Custom dietitian plan", included: true },
      { name: "Custom trainer plan", included: true },
      { name: "4 guest passes/month", included: true },
      { name: "All branches access", included: true },
      { name: "Monthly body comp analysis", included: true },
    ],
    popular: false,
  },
];

// ---- Current Member (logged-in user) ----
export const currentMember = {
  id: "member-1",
  name: "Rahul Sharma",
  email: "rahul.sharma@gmail.com",
  phone: "+91 98765 43210",
  avatar: IMG.trainers[0],
  age: 28,
  height: 175,
  currentWeight: 78.5,
  targetWeight: 72,
  goal: "Build Muscle & Lose Fat",
  experience: "Intermediate",
  memberSince: "2025-09-15",
  plan: "Pro",
  gym: "Iron Paradise Fitness",
  gymId: "gym-1",
  branch: "Koramangala",
  trainer: "Coach Arjun Mehta",
  trainerId: "trainer-1",
  streak: 12,
  totalWorkouts: 156,
  membershipExpiry: "2026-06-15",
  qrCode: "FZ-MEM-2025-00142",
  caloriesBurnedThisWeek: 3240,
  classesThisMonth: 8,
  personalRecords: { benchPress: 85, squat: 110, deadlift: 140 },
};

// ---- Members (for business dashboard) ----
export type MemberStatus = "Active" | "Expired" | "Frozen" | "Trial" | "Lead" | "Cancelled";

export const members = [
  { id: "member-1", name: "Rahul Sharma", email: "rahul.sharma@gmail.com", phone: "+91 98765 43210", avatar: IMG.trainers[0], plan: "Pro", status: "Active" as MemberStatus, joinDate: "2025-09-15", expiry: "2026-06-15", branch: "Koramangala", trainer: "Coach Arjun", lastVisit: "2026-03-26", visits: 156, revenue: 47988 },
  { id: "member-2", name: "Priya Desai", email: "priya.d@gmail.com", phone: "+91 98765 43211", avatar: IMG.trainers[3], plan: "Elite", status: "Active" as MemberStatus, joinDate: "2025-06-01", expiry: "2026-06-01", branch: "Koramangala", trainer: "Deepa Joshi", lastVisit: "2026-03-27", visits: 234, revenue: 95988 },
  { id: "member-3", name: "Vikram Iyer", email: "vikram.iyer@outlook.com", phone: "+91 88765 43212", avatar: IMG.trainers[1], plan: "Elite", status: "Active" as MemberStatus, joinDate: "2025-03-10", expiry: "2026-03-10", branch: "Indiranagar", trainer: "Vikram Singh", lastVisit: "2026-03-25", visits: 312, revenue: 119988 },
  { id: "member-4", name: "Meera Krishnan", email: "meera.k@yahoo.com", phone: "+91 77654 32113", avatar: IMG.trainers[5], plan: "Basic", status: "Active" as MemberStatus, joinDate: "2026-01-05", expiry: "2026-07-05", branch: "Koramangala", trainer: null, lastVisit: "2026-03-24", visits: 45, revenue: 11994 },
  { id: "member-5", name: "Suresh Gowda", email: "suresh.g@gmail.com", phone: "+91 96543 21014", avatar: IMG.trainers[2], plan: "Basic", status: "Expired" as MemberStatus, joinDate: "2025-07-20", expiry: "2026-01-20", branch: "Koramangala", trainer: null, lastVisit: "2026-01-18", visits: 78, revenue: 11994 },
  { id: "member-6", name: "Anita Rao", email: "anita.rao@gmail.com", phone: "+91 99876 54315", avatar: IMG.trainers[7], plan: "Pro", status: "Frozen" as MemberStatus, joinDate: "2025-08-12", expiry: "2026-08-12", branch: "Indiranagar", trainer: "Sneha Reddy", lastVisit: "2026-03-01", visits: 167, revenue: 47988 },
  { id: "member-7", name: "Karthik Nair", email: "karthik.n@proton.me", phone: "+91 88765 43216", avatar: IMG.trainers[4], plan: "Pro", status: "Active" as MemberStatus, joinDate: "2025-11-01", expiry: "2026-05-01", branch: "HSR Layout", trainer: "Coach Arjun", lastVisit: "2026-03-27", visits: 98, revenue: 23994 },
  { id: "member-8", name: "Divya Menon", email: "divya.m@gmail.com", phone: "+91 77654 32117", avatar: IMG.trainers[6], plan: "Elite", status: "Active" as MemberStatus, joinDate: "2025-04-18", expiry: "2026-04-18", branch: "Koramangala", trainer: "Priya Nair", lastVisit: "2026-03-26", visits: 278, revenue: 95988 },
  { id: "member-9", name: "Arjun Patel", email: "arjun.p@gmail.com", phone: "+91 96543 21018", avatar: null, plan: "Basic", status: "Trial" as MemberStatus, joinDate: "2026-03-25", expiry: "2026-03-27", branch: "Koramangala", trainer: null, lastVisit: "2026-03-25", visits: 1, revenue: 0 },
  { id: "member-10", name: "Lakshmi Venkat", email: "lakshmi.v@outlook.com", phone: "+91 88765 43219", avatar: IMG.trainers[5], plan: "Pro", status: "Active" as MemberStatus, joinDate: "2025-10-10", expiry: "2026-04-10", branch: "Indiranagar", trainer: "Ananya Sharma", lastVisit: "2026-03-23", visits: 112, revenue: 23994 },
  { id: "member-11", name: "Rohan Gupta", email: "rohan.g@gmail.com", phone: "+91 99876 54320", avatar: null, plan: null, status: "Lead" as MemberStatus, joinDate: "2026-03-20", expiry: null, branch: "Koramangala", trainer: null, lastVisit: null, visits: 0, revenue: 0 },
  { id: "member-12", name: "Neha Singh", email: "neha.s@gmail.com", phone: "+91 77654 32121", avatar: IMG.trainers[7], plan: "Pro", status: "Cancelled" as MemberStatus, joinDate: "2025-06-15", expiry: "2025-12-15", branch: "HSR Layout", trainer: "Coach Arjun", lastVisit: "2025-12-10", visits: 134, revenue: 23994 },
  { id: "member-13", name: "Amit Jha", email: "amit.jha@gmail.com", phone: "+91 96543 21022", avatar: IMG.trainers[2], plan: "Basic", status: "Active" as MemberStatus, joinDate: "2026-02-01", expiry: "2026-08-01", branch: "Koramangala", trainer: null, lastVisit: "2026-03-27", visits: 34, revenue: 11994 },
  { id: "member-14", name: "Pooja Hegde", email: "pooja.h@yahoo.com", phone: "+91 88765 43223", avatar: IMG.trainers[3], plan: "Elite", status: "Active" as MemberStatus, joinDate: "2025-12-20", expiry: "2026-12-20", branch: "Indiranagar", trainer: "Deepa Joshi", lastVisit: "2026-03-26", visits: 67, revenue: 95988 },
  { id: "member-15", name: "Sanjay Murthy", email: "sanjay.m@gmail.com", phone: "+91 99876 54324", avatar: null, plan: "Pro", status: "Expired" as MemberStatus, joinDate: "2025-05-01", expiry: "2025-11-01", branch: "Koramangala", trainer: null, lastVisit: "2025-10-28", visits: 89, revenue: 23994 },
  { id: "member-16", name: "Tanvi Kulkarni", email: "tanvi.k@proton.me", phone: "+91 77654 32125", avatar: IMG.trainers[6], plan: "Basic", status: "Active" as MemberStatus, joinDate: "2026-03-01", expiry: "2026-09-01", branch: "HSR Layout", trainer: null, lastVisit: "2026-03-25", visits: 12, revenue: 11994 },
  { id: "member-17", name: "Varun Reddy", email: "varun.r@gmail.com", phone: "+91 96543 21026", avatar: IMG.trainers[4], plan: "Pro", status: "Active" as MemberStatus, joinDate: "2025-08-25", expiry: "2026-02-25", branch: "Koramangala", trainer: "Coach Arjun", lastVisit: "2026-03-27", visits: 145, revenue: 23994 },
  { id: "member-18", name: "Ishita Banerjee", email: "ishita.b@gmail.com", phone: "+91 88765 43227", avatar: IMG.trainers[7], plan: null, status: "Lead" as MemberStatus, joinDate: "2026-03-22", expiry: null, branch: "Indiranagar", trainer: null, lastVisit: null, visits: 0, revenue: 0 },
  { id: "member-19", name: "Nikhil Joshi", email: "nikhil.j@outlook.com", phone: "+91 99876 54328", avatar: null, plan: "Basic", status: "Trial" as MemberStatus, joinDate: "2026-03-26", expiry: "2026-03-28", branch: "Koramangala", trainer: null, lastVisit: "2026-03-26", visits: 1, revenue: 0 },
  { id: "member-20", name: "Swati Mishra", email: "swati.m@gmail.com", phone: "+91 77654 32129", avatar: IMG.trainers[5], plan: "Elite", status: "Active" as MemberStatus, joinDate: "2025-07-01", expiry: "2026-07-01", branch: "Koramangala", trainer: "Priya Nair", lastVisit: "2026-03-27", visits: 198, revenue: 95988 },
];

// ---- Exercises ----
export const exercises = [
  { id: "ex-1", name: "Barbell Bench Press", muscleGroup: "Chest", equipment: "Barbell, Bench", difficulty: "Intermediate", image: IMG.gyms[3] },
  { id: "ex-2", name: "Barbell Squat", muscleGroup: "Legs", equipment: "Barbell, Squat Rack", difficulty: "Intermediate", image: IMG.gyms[3] },
  { id: "ex-3", name: "Deadlift", muscleGroup: "Back", equipment: "Barbell", difficulty: "Advanced", image: IMG.gyms[3] },
  { id: "ex-4", name: "Overhead Press", muscleGroup: "Shoulders", equipment: "Barbell", difficulty: "Intermediate", image: IMG.gyms[3] },
  { id: "ex-5", name: "Pull-ups", muscleGroup: "Back", equipment: "Pull-up Bar", difficulty: "Intermediate", image: IMG.gyms[1] },
  { id: "ex-6", name: "Dumbbell Curl", muscleGroup: "Arms", equipment: "Dumbbells", difficulty: "Beginner", image: IMG.gyms[1] },
  { id: "ex-7", name: "Tricep Dips", muscleGroup: "Arms", equipment: "Dip Station", difficulty: "Intermediate", image: IMG.gyms[1] },
  { id: "ex-8", name: "Leg Press", muscleGroup: "Legs", equipment: "Leg Press Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-9", name: "Lat Pulldown", muscleGroup: "Back", equipment: "Cable Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-10", name: "Dumbbell Shoulder Press", muscleGroup: "Shoulders", equipment: "Dumbbells", difficulty: "Beginner", image: IMG.gyms[1] },
  { id: "ex-11", name: "Cable Flyes", muscleGroup: "Chest", equipment: "Cable Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-12", name: "Romanian Deadlift", muscleGroup: "Legs", equipment: "Barbell", difficulty: "Intermediate", image: IMG.gyms[3] },
  { id: "ex-13", name: "Incline Dumbbell Press", muscleGroup: "Chest", equipment: "Dumbbells, Incline Bench", difficulty: "Intermediate", image: IMG.gyms[1] },
  { id: "ex-14", name: "Barbell Row", muscleGroup: "Back", equipment: "Barbell", difficulty: "Intermediate", image: IMG.gyms[3] },
  { id: "ex-15", name: "Lateral Raise", muscleGroup: "Shoulders", equipment: "Dumbbells", difficulty: "Beginner", image: IMG.gyms[1] },
  { id: "ex-16", name: "Leg Extension", muscleGroup: "Legs", equipment: "Leg Extension Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-17", name: "Leg Curl", muscleGroup: "Legs", equipment: "Leg Curl Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-18", name: "Face Pull", muscleGroup: "Shoulders", equipment: "Cable Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-19", name: "Plank", muscleGroup: "Core", equipment: "Bodyweight", difficulty: "Beginner", image: IMG.yoga[2] },
  { id: "ex-20", name: "Russian Twist", muscleGroup: "Core", equipment: "Medicine Ball", difficulty: "Beginner", image: IMG.yoga[2] },
  { id: "ex-21", name: "Hammer Curl", muscleGroup: "Arms", equipment: "Dumbbells", difficulty: "Beginner", image: IMG.gyms[1] },
  { id: "ex-22", name: "Skull Crusher", muscleGroup: "Arms", equipment: "EZ Bar, Bench", difficulty: "Intermediate", image: IMG.gyms[1] },
  { id: "ex-23", name: "Calf Raise", muscleGroup: "Legs", equipment: "Smith Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-24", name: "Hip Thrust", muscleGroup: "Legs", equipment: "Barbell, Bench", difficulty: "Intermediate", image: IMG.gyms[3] },
  { id: "ex-25", name: "Dumbbell Lunge", muscleGroup: "Legs", equipment: "Dumbbells", difficulty: "Beginner", image: IMG.gyms[1] },
  { id: "ex-26", name: "Cable Row", muscleGroup: "Back", equipment: "Cable Machine", difficulty: "Beginner", image: IMG.gyms[6] },
  { id: "ex-27", name: "Chest Dip", muscleGroup: "Chest", equipment: "Dip Station", difficulty: "Intermediate", image: IMG.gyms[1] },
  { id: "ex-28", name: "Hanging Leg Raise", muscleGroup: "Core", equipment: "Pull-up Bar", difficulty: "Intermediate", image: IMG.gyms[1] },
  { id: "ex-29", name: "Battle Ropes", muscleGroup: "Full Body", equipment: "Battle Ropes", difficulty: "Intermediate", image: IMG.gyms[2] },
  { id: "ex-30", name: "Box Jump", muscleGroup: "Legs", equipment: "Plyo Box", difficulty: "Intermediate", image: IMG.gyms[2] },
];

// ---- Workout Plans ----
export const workoutPlans = [
  {
    id: "plan-1",
    name: "Hypertrophy 101",
    goal: "Muscle Gain",
    difficulty: "Intermediate",
    duration: "12 weeks",
    daysPerWeek: 4,
    split: "Upper/Lower",
    description: "A balanced 4-day upper/lower split designed for maximum hypertrophy with progressive overload built in.",
    image: IMG.gyms[3],
    days: [
      { day: "Monday", name: "Upper A", exercises: [{ exerciseId: "ex-1", sets: 4, reps: "8-10", rest: "90s" }, { exerciseId: "ex-14", sets: 4, reps: "8-10", rest: "90s" }, { exerciseId: "ex-4", sets: 3, reps: "10-12", rest: "60s" }, { exerciseId: "ex-6", sets: 3, reps: "12-15", rest: "60s" }, { exerciseId: "ex-7", sets: 3, reps: "10-12", rest: "60s" }] },
      { day: "Tuesday", name: "Lower A", exercises: [{ exerciseId: "ex-2", sets: 4, reps: "6-8", rest: "120s" }, { exerciseId: "ex-12", sets: 3, reps: "10-12", rest: "90s" }, { exerciseId: "ex-8", sets: 3, reps: "12-15", rest: "60s" }, { exerciseId: "ex-17", sets: 3, reps: "12-15", rest: "60s" }, { exerciseId: "ex-23", sets: 4, reps: "15-20", rest: "45s" }] },
      { day: "Thursday", name: "Upper B", exercises: [{ exerciseId: "ex-13", sets: 4, reps: "10-12", rest: "90s" }, { exerciseId: "ex-5", sets: 4, reps: "6-10", rest: "90s" }, { exerciseId: "ex-15", sets: 4, reps: "12-15", rest: "60s" }, { exerciseId: "ex-21", sets: 3, reps: "12-15", rest: "60s" }, { exerciseId: "ex-22", sets: 3, reps: "10-12", rest: "60s" }] },
      { day: "Friday", name: "Lower B", exercises: [{ exerciseId: "ex-3", sets: 4, reps: "5-6", rest: "180s" }, { exerciseId: "ex-24", sets: 3, reps: "10-12", rest: "90s" }, { exerciseId: "ex-25", sets: 3, reps: "12/leg", rest: "60s" }, { exerciseId: "ex-16", sets: 3, reps: "15-20", rest: "60s" }, { exerciseId: "ex-28", sets: 3, reps: "12-15", rest: "60s" }] },
    ],
  },
  {
    id: "plan-2",
    name: "Shred30",
    goal: "Fat Loss",
    difficulty: "Beginner",
    duration: "8 weeks",
    daysPerWeek: 5,
    split: "Full Body + Cardio",
    description: "An intense 5-day fat-loss program combining metabolic resistance training with strategic HIIT sessions.",
    image: IMG.gyms[2],
    days: [
      { day: "Monday", name: "Full Body Strength", exercises: [{ exerciseId: "ex-2", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-1", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-14", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-25", sets: 3, reps: "12/leg", rest: "60s" }] },
      { day: "Tuesday", name: "HIIT Cardio", exercises: [{ exerciseId: "ex-29", sets: 5, reps: "30s", rest: "30s" }, { exerciseId: "ex-30", sets: 5, reps: "10", rest: "30s" }, { exerciseId: "ex-19", sets: 3, reps: "45s", rest: "15s" }] },
      { day: "Wednesday", name: "Upper Body", exercises: [{ exerciseId: "ex-13", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-9", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-10", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-6", sets: 3, reps: "15", rest: "45s" }] },
      { day: "Thursday", name: "HIIT Cardio", exercises: [{ exerciseId: "ex-29", sets: 5, reps: "30s", rest: "30s" }, { exerciseId: "ex-30", sets: 5, reps: "10", rest: "30s" }, { exerciseId: "ex-20", sets: 3, reps: "20", rest: "30s" }] },
      { day: "Friday", name: "Lower Body", exercises: [{ exerciseId: "ex-8", sets: 3, reps: "15", rest: "60s" }, { exerciseId: "ex-12", sets: 3, reps: "12", rest: "60s" }, { exerciseId: "ex-17", sets: 3, reps: "15", rest: "60s" }, { exerciseId: "ex-23", sets: 3, reps: "20", rest: "45s" }] },
    ],
  },
];

// ---- Body Metrics (6 months of history for current member) ----
export const bodyMetrics = {
  weightHistory: [
    { date: "2025-10-01", value: 82.3 },
    { date: "2025-10-15", value: 81.8 },
    { date: "2025-11-01", value: 81.2 },
    { date: "2025-11-15", value: 80.5 },
    { date: "2025-12-01", value: 80.1 },
    { date: "2025-12-15", value: 79.8 },
    { date: "2026-01-01", value: 80.2 },
    { date: "2026-01-15", value: 79.6 },
    { date: "2026-02-01", value: 79.1 },
    { date: "2026-02-15", value: 78.9 },
    { date: "2026-03-01", value: 78.7 },
    { date: "2026-03-15", value: 78.5 },
  ],
  bodyFatHistory: [
    { date: "2025-10-01", value: 22.5 },
    { date: "2025-12-01", value: 20.8 },
    { date: "2026-01-01", value: 20.1 },
    { date: "2026-02-01", value: 19.4 },
    { date: "2026-03-01", value: 18.8 },
  ],
  measurements: {
    chest: [{ date: "2025-10-01", value: 96 }, { date: "2026-01-01", value: 99 }, { date: "2026-03-01", value: 101 }],
    waist: [{ date: "2025-10-01", value: 88 }, { date: "2026-01-01", value: 85 }, { date: "2026-03-01", value: 83 }],
    hips: [{ date: "2025-10-01", value: 98 }, { date: "2026-01-01", value: 96 }, { date: "2026-03-01", value: 95 }],
    biceps: [{ date: "2025-10-01", value: 33 }, { date: "2026-01-01", value: 35 }, { date: "2026-03-01", value: 36.5 }],
    thigh: [{ date: "2025-10-01", value: 56 }, { date: "2026-01-01", value: 57 }, { date: "2026-03-01", value: 58 }],
  },
  bmi: 25.6,
  bmr: 1780,
  muscleMass: 35.2,
};

// ---- Nutrition Data ----
export const nutritionData = {
  dailyTarget: { calories: 2200, protein: 165, carbs: 220, fat: 73 },
  todayIntake: { calories: 1680, protein: 128, carbs: 175, fat: 52 },
  meals: [
    { id: "meal-1", name: "Breakfast", time: "7:30 AM", items: [{ name: "Oats with Banana & Almonds", calories: 380, protein: 14, carbs: 58, fat: 12, image: IMG.food[0] }, { name: "Protein Shake (Whey + Milk)", calories: 220, protein: 32, carbs: 12, fat: 5, image: IMG.food[1] }] },
    { id: "meal-2", name: "Lunch", time: "1:00 PM", items: [{ name: "Chicken Breast Curry with Brown Rice", calories: 520, protein: 42, carbs: 55, fat: 14, image: IMG.food[2] }, { name: "Mixed Green Salad", calories: 80, protein: 3, carbs: 12, fat: 3, image: IMG.food[3] }] },
    { id: "meal-3", name: "Post-Workout Snack", time: "5:30 PM", items: [{ name: "Paneer Tikka (6 pcs)", calories: 280, protein: 22, carbs: 8, fat: 18, image: IMG.food[4] }] },
    { id: "meal-4", name: "Dinner", time: "8:30 PM", items: [{ name: "Dal Tadka with 2 Roti", calories: 420, protein: 18, carbs: 62, fat: 10, image: IMG.food[5] }] },
  ],
  weeklyAverage: { calories: 2050, protein: 152, carbs: 205, fat: 68 },
  dietPlan: "High-Protein Non-Veg",
};

// ---- Revenue Data (for business dashboard) ----
export const revenueData = {
  totalRevenue: 824000,
  monthlyRevenue: [
    { month: "Oct", revenue: 620000, expenses: 380000 },
    { month: "Nov", revenue: 680000, expenses: 395000 },
    { month: "Dec", revenue: 710000, expenses: 410000 },
    { month: "Jan", revenue: 780000, expenses: 420000 },
    { month: "Feb", revenue: 795000, expenses: 425000 },
    { month: "Mar", revenue: 824000, expenses: 435000 },
  ],
  breakdown: [
    { category: "Memberships", amount: 485000, percentage: 59 },
    { category: "PT Sessions", amount: 168000, percentage: 20 },
    { category: "Group Classes", amount: 82000, percentage: 10 },
    { category: "Supplements", amount: 49000, percentage: 6 },
    { category: "Guest Passes", amount: 24000, percentage: 3 },
    { category: "Merchandise", amount: 16000, percentage: 2 },
  ],
  mrr: 485000,
  mrrGrowth: 8.2,
  overduePayments: 48000,
  overdueCount: 12,
  refundsThisMonth: 12000,
  avgRevenuePerMember: 4200,
};

// ---- Leads ----
export type LeadStage = "New" | "Contacted" | "Trial Booked" | "Trial Complete" | "Follow-up" | "Converted" | "Lost";

export const leads = [
  { id: "lead-1", name: "Rohan Gupta", phone: "+91 99876 54320", email: "rohan.g@gmail.com", source: "Google Ads", stage: "New" as LeadStage, assignedTo: "Front Desk - Deepak", date: "2026-03-20", notes: "Interested in CrossFit", branch: "Koramangala" },
  { id: "lead-2", name: "Ishita Banerjee", phone: "+91 88765 43227", email: "ishita.b@gmail.com", source: "Instagram", stage: "Trial Booked" as LeadStage, assignedTo: "Sales - Priyanka", date: "2026-03-22", notes: "Wants women-friendly environment, booked trial for Mar 28", branch: "Indiranagar" },
  { id: "lead-3", name: "Nikhil Joshi", phone: "+91 99876 54328", email: "nikhil.j@outlook.com", source: "Walk-in", stage: "Trial Complete" as LeadStage, assignedTo: "Front Desk - Deepak", date: "2026-03-26", notes: "Completed trial, impressed with equipment. Budget concern - suggest Basic plan", branch: "Koramangala" },
  { id: "lead-4", name: "Kavya Nair", phone: "+91 77654 32130", email: "kavya.n@gmail.com", source: "Referral - Priya Desai", stage: "Contacted" as LeadStage, assignedTo: "Sales - Priyanka", date: "2026-03-18", notes: "Called, interested but checking other options", branch: "Koramangala" },
  { id: "lead-5", name: "Ajay Mehta", phone: "+91 96543 21031", email: "ajay.m@yahoo.com", source: "FitZone App", stage: "Follow-up" as LeadStage, assignedTo: "Sales - Priyanka", date: "2026-03-15", notes: "Requested callback, was busy at first attempt", branch: "HSR Layout" },
  { id: "lead-6", name: "Shreya Das", phone: "+91 88765 43232", email: "shreya.d@gmail.com", source: "Google Ads", stage: "Converted" as LeadStage, assignedTo: "Sales - Priyanka", date: "2026-03-10", notes: "Joined Pro plan on Mar 18", branch: "Koramangala" },
  { id: "lead-7", name: "Vishal Kumar", phone: "+91 99876 54333", email: "vishal.k@gmail.com", source: "Walk-in", stage: "Lost" as LeadStage, assignedTo: "Front Desk - Deepak", date: "2026-03-08", notes: "Price too high, went to FitBudget instead", branch: "Koramangala" },
  { id: "lead-8", name: "Tanya Sharma", phone: "+91 77654 32134", email: "tanya.s@proton.me", source: "Instagram", stage: "Trial Booked" as LeadStage, assignedTo: "Sales - Priyanka", date: "2026-03-25", notes: "Booked trial for Mar 29, interested in Zumba", branch: "Indiranagar" },
];

// ---- Equipment ----
export type EquipmentStatus = "Working" | "Under Maintenance" | "Out of Service";

export const equipment = [
  { id: "eq-1", name: "Treadmill - Life Fitness", model: "T5", quantity: 8, working: 7, status: "Working" as EquipmentStatus, purchaseDate: "2022-06-15", warrantyExpiry: "2027-06-15", lastMaintenance: "2026-02-20", nextMaintenance: "2026-05-20", location: "Cardio Zone", branch: "Koramangala" },
  { id: "eq-2", name: "Smith Machine - Hammer Strength", model: "HS-4000", quantity: 2, working: 2, status: "Working" as EquipmentStatus, purchaseDate: "2021-03-10", warrantyExpiry: "2026-03-10", lastMaintenance: "2026-01-15", nextMaintenance: "2026-04-15", location: "Strength Zone", branch: "Koramangala" },
  { id: "eq-3", name: "Treadmill - Life Fitness", model: "T5", quantity: 1, working: 0, status: "Under Maintenance" as EquipmentStatus, purchaseDate: "2022-06-15", warrantyExpiry: "2027-06-15", lastMaintenance: "2026-03-25", nextMaintenance: "2026-03-30", location: "Cardio Zone", branch: "Koramangala" },
  { id: "eq-4", name: "Cable Crossover - Precor", model: "FTS Glide", quantity: 3, working: 3, status: "Working" as EquipmentStatus, purchaseDate: "2023-01-20", warrantyExpiry: "2028-01-20", lastMaintenance: "2026-03-01", nextMaintenance: "2026-06-01", location: "Strength Zone", branch: "Koramangala" },
  { id: "eq-5", name: "Spin Bike - Keiser", model: "M3i", quantity: 15, working: 14, status: "Working" as EquipmentStatus, purchaseDate: "2023-08-10", warrantyExpiry: "2026-08-10", lastMaintenance: "2026-02-10", nextMaintenance: "2026-05-10", location: "Spin Studio", branch: "Koramangala" },
  { id: "eq-6", name: "Rowing Machine - Concept2", model: "Model D", quantity: 4, working: 4, status: "Working" as EquipmentStatus, purchaseDate: "2022-11-05", warrantyExpiry: "2027-11-05", lastMaintenance: "2026-01-20", nextMaintenance: "2026-04-20", location: "Cardio Zone", branch: "Koramangala" },
  { id: "eq-7", name: "Leg Press - Cybex", model: "Eagle NX", quantity: 2, working: 1, status: "Out of Service" as EquipmentStatus, purchaseDate: "2020-09-15", warrantyExpiry: "2025-09-15", lastMaintenance: "2026-03-10", nextMaintenance: null, location: "Leg Zone", branch: "Koramangala" },
  { id: "eq-8", name: "Dumbbells Set - Eleiko", model: "Vulcano", quantity: 1, working: 1, status: "Working" as EquipmentStatus, purchaseDate: "2022-01-01", warrantyExpiry: "2032-01-01", lastMaintenance: "2026-02-15", nextMaintenance: "2026-08-15", location: "Free Weights", branch: "Koramangala" },
];

// ---- Challenges & Gamification ----
export const challenges = [
  { id: "ch-1", name: "30-Day Plank Challenge", description: "Hold a plank every day, increasing from 30s to 5min over 30 days", type: "Individual", startDate: "2026-03-01", endDate: "2026-03-31", participants: 145, image: IMG.yoga[2], prize: "1 Month Free Extension", status: "Active" },
  { id: "ch-2", name: "10K Steps Daily", description: "Walk 10,000+ steps every day for 21 days straight", type: "Individual", startDate: "2026-03-10", endDate: "2026-03-31", participants: 230, image: IMG.gyms[2], prize: "FitZone Merch Hamper", status: "Active" },
  { id: "ch-3", name: "March Body Transformation", description: "90-day body transformation challenge — judged by % body fat reduced and muscle gained", type: "Competitive", startDate: "2026-01-01", endDate: "2026-03-31", participants: 48, image: IMG.gyms[0], prize: "₹25,000 Cash + 6 Months Free", status: "Active" },
  { id: "ch-4", name: "Most Gym Visits - Feb", description: "Member with most gym check-ins in February wins", type: "Competitive", startDate: "2026-02-01", endDate: "2026-02-28", participants: 320, image: IMG.gyms[1], prize: "Free PT Pack (5 sessions)", status: "Completed" },
];

export const leaderboard = [
  { rank: 1, memberId: "member-3", name: "Vikram Iyer", avatar: IMG.trainers[1], score: 28, metric: "visits this month" },
  { rank: 2, memberId: "member-2", name: "Priya Desai", avatar: IMG.trainers[3], score: 26, metric: "visits this month" },
  { rank: 3, memberId: "member-20", name: "Swati Mishra", avatar: IMG.trainers[5], score: 24, metric: "visits this month" },
  { rank: 4, memberId: "member-8", name: "Divya Menon", avatar: IMG.trainers[6], score: 22, metric: "visits this month" },
  { rank: 5, memberId: "member-1", name: "Rahul Sharma", avatar: IMG.trainers[0], score: 20, metric: "visits this month" },
  { rank: 6, memberId: "member-7", name: "Karthik Nair", avatar: IMG.trainers[4], score: 18, metric: "visits this month" },
  { rank: 7, memberId: "member-17", name: "Varun Reddy", avatar: IMG.trainers[4], score: 17, metric: "visits this month" },
  { rank: 8, memberId: "member-14", name: "Pooja Hegde", avatar: IMG.trainers[3], score: 15, metric: "visits this month" },
  { rank: 9, memberId: "member-4", name: "Meera Krishnan", avatar: IMG.trainers[5], score: 13, metric: "visits this month" },
  { rank: 10, memberId: "member-13", name: "Amit Jha", avatar: IMG.trainers[2], score: 12, metric: "visits this month" },
];

export const badges = [
  { id: "badge-1", name: "First Workout", icon: "🏋️", description: "Completed your first workout", earned: true, date: "2025-09-16" },
  { id: "badge-2", name: "10-Day Streak", icon: "🔥", description: "Visited the gym 10 days in a row", earned: true, date: "2025-10-12" },
  { id: "badge-3", name: "Century Club", icon: "💯", description: "Completed 100 workouts", earned: true, date: "2026-01-28" },
  { id: "badge-4", name: "Class Explorer", icon: "🎯", description: "Tried 5 different class types", earned: true, date: "2025-11-20" },
  { id: "badge-5", name: "5 Kg Down", icon: "⚖️", description: "Lost 5 kg from starting weight", earned: false, date: null },
  { id: "badge-6", name: "1-Year Member", icon: "⭐", description: "Active member for 1 year", earned: false, date: null },
  { id: "badge-7", name: "PR Breaker", icon: "🏆", description: "Set a new personal record", earned: true, date: "2026-03-15" },
  { id: "badge-8", name: "Social Butterfly", icon: "🦋", description: "Referred 3 friends who joined", earned: false, date: null },
];

// ---- Reviews ----
export const reviews = [
  { id: "rev-1", gymId: "gym-1", memberId: "member-2", memberName: "Priya Desai", avatar: IMG.trainers[3], rating: 5, date: "2026-03-15", text: "Best gym in Koramangala! The trainers are incredibly supportive, and the equipment is always in top shape. The steam room is my favorite post-workout treat.", categories: { equipment: 5, cleanliness: 5, trainers: 5, value: 4 } },
  { id: "rev-2", gymId: "gym-1", memberId: "member-3", memberName: "Vikram Iyer", avatar: IMG.trainers[1], rating: 4, date: "2026-02-28", text: "Great equipment selection and knowledgeable trainers. Only gripe is parking can be tight during evening rush hours. Otherwise, solid 4-star experience.", categories: { equipment: 5, cleanliness: 4, trainers: 5, value: 4 } },
  { id: "rev-3", gymId: "gym-1", memberId: "member-4", memberName: "Meera Krishnan", avatar: IMG.trainers[5], rating: 5, date: "2026-01-10", text: "As a complete beginner, I was nervous about joining a gym. The staff here made me feel welcome from day one. The beginner-friendly classes are perfect.", categories: { equipment: 4, cleanliness: 5, trainers: 5, value: 5 } },
  { id: "rev-4", gymId: "gym-1", memberId: "member-5", memberName: "Suresh Gowda", avatar: IMG.trainers[2], rating: 3, date: "2025-12-20", text: "Decent gym but the AC in the weight area breaks down frequently during summer. Management has been responsive to complaints though.", categories: { equipment: 4, cleanliness: 3, trainers: 4, value: 3 } },
];

// ---- Notifications ----
export const notifications = [
  { id: "notif-1", type: "class", title: "Class Reminder", message: "HIIT Burn with Coach Arjun starts in 1 hour at Main Floor", time: "55 min ago", read: false, icon: "calendar" },
  { id: "notif-2", type: "milestone", title: "Streak Alert! 🔥", message: "You've hit a 12-day gym streak! Keep it up!", time: "2 hours ago", read: false, icon: "trophy" },
  { id: "notif-3", type: "plan", title: "Workout Plan Updated", message: "Coach Arjun updated your Thursday routine — added Face Pulls for shoulder health", time: "Yesterday", read: true, icon: "clipboard" },
  { id: "notif-4", type: "payment", title: "Payment Successful", message: "₹3,999 paid for Pro membership. Active until June 15, 2026", time: "3 days ago", read: true, icon: "credit-card" },
  { id: "notif-5", type: "achievement", title: "PR Breaker Badge Unlocked! 🏆", message: "New bench press personal record: 85 kg! You crushed it!", time: "Mar 15", read: true, icon: "award" },
  { id: "notif-6", type: "social", title: "Challenge Update", message: "You're #5 on the March gym visits leaderboard. 8 more visits to reach #3!", time: "Mar 20", read: true, icon: "bar-chart" },
  { id: "notif-7", type: "offer", title: "Renewal Offer", message: "Your membership expires in 80 days. Renew now and get 10% off!", time: "Mar 22", read: true, icon: "tag" },
];

// ---- Trainer Earnings (for trainer panel) ----
export const trainerEarnings = {
  currentMonth: {
    totalSessions: 42,
    totalEarnings: 50400,
    commission: 42840,
    pending: 7560,
  },
  history: [
    { month: "Oct 2025", sessions: 38, earnings: 45600, commission: 38760 },
    { month: "Nov 2025", sessions: 40, earnings: 48000, commission: 40800 },
    { month: "Dec 2025", sessions: 35, earnings: 42000, commission: 35700 },
    { month: "Jan 2026", sessions: 44, earnings: 52800, commission: 44880 },
    { month: "Feb 2026", sessions: 41, earnings: 49200, commission: 41820 },
    { month: "Mar 2026", sessions: 42, earnings: 50400, commission: 42840 },
  ],
  commissionRate: 85,
  payoutSchedule: "1st and 15th of every month",
  nextPayout: "2026-04-01",
  nextPayoutAmount: 21420,
};

// ---- Trainer Schedule (for trainer panel) ----
export const trainerSchedule = [
  { id: "ts-1", type: "PT Session", client: "Rahul Sharma", clientId: "member-1", date: "2026-03-27", time: "7:00 AM", duration: 60, status: "Upcoming", notes: "Focus on chest & back, increase bench press" },
  { id: "ts-2", type: "Group Class", class: "HIIT Burn", date: "2026-03-27", time: "8:30 AM", duration: 45, status: "Upcoming", participants: 25 },
  { id: "ts-3", type: "PT Session", client: "Karthik Nair", clientId: "member-7", date: "2026-03-27", time: "10:00 AM", duration: 60, status: "Upcoming", notes: "Leg day, knee rehab exercises" },
  { id: "ts-4", type: "PT Session", client: "Varun Reddy", clientId: "member-17", date: "2026-03-27", time: "11:30 AM", duration: 60, status: "Upcoming", notes: "Upper body hypertrophy focus" },
  { id: "ts-5", type: "PT Session", client: "Priya Desai", clientId: "member-2", date: "2026-03-28", time: "7:00 AM", duration: 60, status: "Scheduled", notes: "HIIT circuit + core" },
  { id: "ts-6", type: "Group Class", class: "HIIT Burn", date: "2026-03-28", time: "8:30 AM", duration: 45, status: "Scheduled", participants: 22 },
  { id: "ts-7", type: "PT Session", client: "Divya Menon", clientId: "member-8", date: "2026-03-28", time: "10:00 AM", duration: 60, status: "Scheduled", notes: "Functional training" },
  { id: "ts-8", type: "PT Session", client: "Rahul Sharma", clientId: "member-1", date: "2026-03-26", time: "7:00 AM", duration: 60, status: "Completed", notes: "Leg day — squat PR attempt" },
  { id: "ts-9", type: "Group Class", class: "Boot Camp", date: "2026-03-22", time: "7:00 AM", duration: 60, status: "Completed", participants: 22 },
];

// ---- Trainer Client Notes ----
export const trainerClientNotes = [
  { clientId: "member-1", clientName: "Rahul Sharma", notes: [{ date: "2026-03-26", text: "Excellent session. Squat form improved significantly. Attempted 115 kg squat — got 2 clean reps. Progressing well toward 120 kg goal." }, { date: "2026-03-20", text: "Bench press PR: 85 kg x 3. Shoulder mobility still needs work — added face pulls to routine." }] },
  { clientId: "member-7", clientName: "Karthik Nair", notes: [{ date: "2026-03-25", text: "Right knee still sensitive during deep squats. Modified to box squats at parallel depth. Added extra hamstring and VMO work." }] },
  { clientId: "member-17", clientName: "Varun Reddy", notes: [{ date: "2026-03-24", text: "Good energy today. Increased all upper body lifts by 2.5 kg. Discussed nutrition — protein intake still below target, recommended increasing chicken/paneer portions." }] },
];

// ---- Attendance Heatmap Data ----
export const attendanceHeatmap = {
  hourly: [
    { hour: "5 AM", mon: 12, tue: 10, wed: 14, thu: 11, fri: 13, sat: 18, sun: 5 },
    { hour: "6 AM", mon: 28, tue: 25, wed: 30, thu: 26, fri: 29, sat: 35, sun: 10 },
    { hour: "7 AM", mon: 42, tue: 38, wed: 45, thu: 40, fri: 43, sat: 48, sun: 15 },
    { hour: "8 AM", mon: 35, tue: 32, wed: 38, thu: 34, fri: 36, sat: 42, sun: 12 },
    { hour: "9 AM", mon: 20, tue: 18, wed: 22, thu: 19, fri: 21, sat: 30, sun: 8 },
    { hour: "10 AM", mon: 15, tue: 14, wed: 16, thu: 15, fri: 15, sat: 25, sun: 6 },
    { hour: "11 AM", mon: 12, tue: 10, wed: 13, thu: 11, fri: 12, sat: 18, sun: 4 },
    { hour: "12 PM", mon: 8, tue: 7, wed: 9, thu: 8, fri: 8, sat: 10, sun: 3 },
    { hour: "1 PM", mon: 6, tue: 5, wed: 7, thu: 6, fri: 6, sat: 8, sun: 2 },
    { hour: "4 PM", mon: 18, tue: 16, wed: 20, thu: 17, fri: 19, sat: 12, sun: 5 },
    { hour: "5 PM", mon: 32, tue: 30, wed: 35, thu: 31, fri: 33, sat: 20, sun: 8 },
    { hour: "6 PM", mon: 45, tue: 42, wed: 48, thu: 44, fri: 46, sat: 25, sun: 10 },
    { hour: "7 PM", mon: 40, tue: 38, wed: 43, thu: 39, fri: 41, sat: 18, sun: 8 },
    { hour: "8 PM", mon: 28, tue: 25, wed: 30, thu: 27, fri: 29, sat: 12, sun: 5 },
    { hour: "9 PM", mon: 15, tue: 13, wed: 17, thu: 14, fri: 16, sat: 8, sun: 3 },
    { hour: "10 PM", mon: 8, tue: 6, wed: 9, thu: 7, fri: 8, sat: 4, sun: 1 },
  ],
  todayTotal: 187,
  weekTotal: 1245,
  monthTotal: 5420,
  peakHour: "6:00 PM - 7:00 PM",
};

// ---- Business Dashboard Stats ----
export const businessStats = {
  totalMembers: 850,
  activeMembers: 680,
  newMembersThisMonth: 28,
  memberGrowth: 5.2,
  totalTrainers: 12,
  classFillRate: 78,
  avgDailyCheckIns: 187,
  memberRetentionRate: 82,
  expiringThisMonth: 47,
  overduePayments: 12,
  trialConversionRate: 62,
  nps: 72,
};
